# Simulation of smeared FoM 

1. For the first decay step, a random τ1was picked according to the τlikelihood function h(τ ) (see Fig. 4). Fourteen random lifetimes from the exponential distribution g(t)defined by this τ1were generated. 
2. For the second decay step, a random τ2was picked according to the τlikelihood function  h(τ ). Fourteen random lifetimes from the exponential distribution g(t)defined by this τ 2 were generated. 
3. For the third decay step, a random τ3was picked according to the τlikelihood function  h(τ ). Ten random lifetimes from the exponential distribution g(t)defined by this τ3were  generated. 
4. The generated lifetimes were collected in fourteen chains – ten with three lifetimes, and four  with two lifetimes.

In [1]:
import numpy as np
import os, sys, yaml, re
from IPython.display import display, Markdown, Latex #Can write latex too!!!!

In [3]:
class DecayChain(yaml.YAMLObject):
    
    yaml_tag = u'!DecayChain'
    
    def __init__(self, idd="", be="", pi="", ie="", it="", ea=[], eas=[], ta=[]):
        self.ID = idd
        self.BeamEnergy = be
        self.Pixel = pi
        self.ImplantEnergy = ie
        self.ImplantTime = it
        self.EAlpha, self.EAlphaSigma, self.TAlpha = ea, eas, ta

class SetDecayChains:
    
    def __init__(self, path='', ids=[]):
        s_files = " ".join(os.listdir(path))
        files = []
        for s in ids:
            files += (sorted(re.findall(string=s_files, pattern="Chain"+s+"\d+.yml")))
        print("Reading the following files:", files)
        self.Chains = []
        for f in files:
            f_in = open(path+f, 'r')
            self.Chains.append(yaml.load(f_in))
            f_in.close()

In [4]:
s_path = "E115_Chains/"
s_id = ["14", "11", "17"]

setDC = SetDecayChains(s_path, s_id)
max_steps = 0
for chain in setDC.Chains:
    if len(chain.TAlpha) > max_steps:
        max_steps = len(chain.TAlpha)
print("Max steps=", max_steps)
times = np.zeros((len(setDC.Chains), max_steps))
for row, chain in enumerate(setDC.Chains):
    steps = len(chain.TAlpha)
    for i in range(max_steps):
        if i < steps:
            times[row][i] = chain.TAlpha[i]
        else:
            times[row][i] = np.nan       
times

Reading the following files: ['Chain1401.yml', 'Chain1402.yml', 'Chain1403.yml', 'Chain1404.yml', 'Chain1405.yml', 'Chain1406.yml', 'Chain1407.yml', 'Chain1101.yml', 'Chain1102.yml', 'Chain1103.yml', 'Chain1104.yml', 'Chain1701.yml', 'Chain1702.yml', 'Chain1703.yml']
Max steps= 3


array([[  2.27000000e-01,   3.78000000e-01,              nan],
       [  6.45000000e-02,   3.66000000e-01,              nan],
       [  2.61000000e-01,   1.15000000e+00,   3.43000000e-01],
       [  1.46000000e+00,   2.62000000e-02,   4.32000000e-01],
       [  3.45000000e-01,   3.69000000e-01,   1.44000000e+01],
       [  2.10000000e-01,   1.05000000e+00,   8.27000000e+00],
       [  8.15000000e-01,   2.33000000e+00,   2.89000000e+00],
       [  2.56200000e-01,   1.40270000e+00,   1.97750000e+00],
       [  6.61000000e-02,   1.55000000e+00,   2.36380000e+00],
       [  2.35070000e+00,   2.25822000e+01,   6.01855000e+01],
       [  5.36000000e-02,   4.67100000e-01,   9.08000000e-02],
       [  2.14000000e-01,   1.54000000e+00,   7.57000000e+00],
       [  5.91000000e-02,   8.24000000e-01,              nan],
       [  4.55000000e-02,   1.42000000e-02,              nan]])

In [22]:
N_j = np.count_nonzero(~np.isnan(times), axis=0)
N_j

array([14, 14, 10])

In [23]:
t_mean_j = np.nanmean(times, axis=0)
t_mean_j

array([ 0.45912143,  2.4321    ,  9.85226   ])

In [34]:
class tau_likelihood_func:
    def __init__(self, t_mean, N_j):
        self.t_mean = t_mean
        self.N_j = N_j
        self.factor1 = np.divide(np.multiply(np.power(self.N_j, self.N_j-1), np.power(self.t_mean, self.N_j-1)), factorial() 

    def __call__(self, tau):
        ret = np.empty((len(tau), len(self.N_j)))
        np.exp(np.multiply(self.N_j))
        return 0

tau_likelihood = tau_likelihood_func(t_mean_j, N_j)

In [35]:
tau = np.linspace(0, max(t_mean_j)*5, 1000)
print(len(tau))
tau_likelihood(tau)

1000


0

In [37]:
from scipy.special import factorial
factorial(np.array([2, 3]))

array([ 2.,  6.])

For each step j, the likelihood function for the true lifetime τj, given by Njand  ̄tj, is  determined. 

For each step j, a τjis selected with a probability governed by the likelihood function for  τj, and then a set of Njlifetimes are generated from the exponential distribution defined by  this τj. This procedure is repeated until a smooth histogram emerges.